language: node_js
node_js:
  - '14'
services:
  - mysql

branches:
  only:
    - master
env:
  global:
    - DB_USERNAME=root
    - DB_PASSWORD=
    - DB_PORT=3306

script:
  - npm i
  - npm run lint
  - npm test

before_install:
- mysql -e 'CREATE DATABASE IF NOT EXISTS test_example;'

after_success: npm run test:coverage:coveralls