language: node_js
node_js:
  - '14'
services:
  - mysql
cache: npm
branches:
  only:
    - master
env:
  global:
    - DB_PASSWORD=
    - DB_PORT=3306

script:
  - npm run lint
  - npm test

before_install:
- mysql -e 'CREATE DATABASE IF NOT EXISTS test_example;'

# after_success: npm run coverage:coveralls