language: node_js
node_js:
  - '14'
services:
  - mysql
cache: npm
branches:
  only:
    - master
env:
  global:
    - DB_PASSWORD=
    - DB_PORT=3306

script:
  - npm run lint
  - npm test

after_success: npm run coverage:coveralls