image:
  repository: ismaelalvesdoc/express-example
  tag: latest
  pullPolicy: IfNotPresent

service:
  enabled: true
  type: NodePort

env:
  NODE_ENV: development
  TIME_ZONE: America/Fortaleza
  HTTP_ACTIVE: true
  AMQP_ACTIVE: true
  SERVER_SSL: false
  SERVER_PORT: 3000
  SERVER_BODY_LIMIT: 500kb
  SSL_CERT:
  SSL_KEY: 
  AMQP_PROTOCOL: amqp
  AMQP_HOSTNAME: localhost
  AMQP_PORT: 5672
  AMQP_USERNAME: admin
  AMQP_PASSWORD: admin
  AMQP_VHOST: /
  DB_HOST: localhost
  DB_PORT: 3306
  DB_USERNAME: root
  DB_DATABASE: example
  DB_DEBUG: false
  REDIS_HOST: localhost
  REDIS_PORT: 6379
  REDIS_PREFIX: example
  APM_SERVER_URL: http://localhost:8200
  APM_SERVICE_NAME: example
  APM_API_KEY: 
  APM_SECRET_TOKEN: 
  EMAIL_TYPE: gmail
  EMAIL_HOST: smtp.gmail.com
  EMAIL_PORT: 465
  EMAIL_SECURE: true
  EMAIL_USER: 
  EMAIL_PASSWORD: 
  EMAIL_OAUTH2_CLIENTID: 
  EMAIL_OAUTH2_CLIENTSECRET: 
  EMAIL_OAUTH2_REFRESHTOKEN: 
  EMAIL_OAUTH2_REDIRECT_URI: 

secret:
  DB_PASSWORD: admin

replicaCount: 1

resources:
  requests:
    memory: "128Mi"
    cpu: 100m
  limits:
    memory: "500Mi"
    cpu: 200m

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: 60
  - type: Resource
    resource:
      name: memory
      targetAverageUtilization: 60