apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: example-api-autoscaler
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: cexample-api
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 50