apiVersion: v1
kind: Service
metadata:
  name: example-api
spec:
  selector:
    app: example-api
  ports:
  - port: 3000
    nodePort: 31000
    targetPort: example-api-port
    protocol: TCP
  type: NodePort