apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "service.fullname" . }}
  labels: {{ include "service.labels" . | nindent 4 }}
  {{- if .Values.namespace }}
  namespace: {{ .Values.namespace }}
  {{- end}}
data:
  {{- range $key, $value := .Values.secret }}
  {{ $key | upper }}: {{ $value | toString | b64enc | quote }}
  {{- end }}
